HospitalWebProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web_app.urls")),
    path('', include("guides.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # Serving media files
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
]

guides/urls.py
from django.urls import path
from .views import *

app_name = "guides"

urlpatterns = [
    path('articles/', HomePageView.as_view(), name="home_url"),
    path('articles/<slug:category_slug>/', HomePageView.as_view(), name="category_url"),
    path('<slug:url_slug>/', BlogView.as_view(), name="blog_url"),
]

web_app/urls.py
from django.urls import path
from .views import *

app_name = "web_app"

urlpatterns = [
    path("", HomePageView.as_view(), name="home_url"),
    path("doctors/<slug:doctor_slug>/", DoctorPageView.as_view(), name="doctor_url"),
    path('contact-us/', contact, name="contact_us_url"),
    path('services/<slug:service_name>/',services,name='services'),
    path('about-us/',about_us.as_view(),name='about_us'),
]

guides/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from web_app.models import Doctor, Business
from django.utils.text import slugify
from bs4 import BeautifulSoup


class Blog(models.Model):
    STATUS_CHOICE = (
        ("draft", "Draft"), 
        ("published", "Published")
    )
    meta_title = models.CharField(max_length=500)
    meta_desc = models.CharField(max_length=500)
    url_slug = models.SlugField(max_length=500, unique=True)
    content = RichTextUploadingField()
    toc = RichTextUploadingField(verbose_name="Table of Content", null=True, blank=True)
    featured_image = models.ImageField(upload_to="guides_featured_image/",null=True,blank=True)
    category = models.CharField(max_length=255, null=True, blank=True)
    publisher = models.ForeignKey(Business, on_delete=models.CASCADE)
    created_by = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name="blog_created_by")
    reviewed_by = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name="blog_reviewed_by")
    reviewed_at = models.DateTimeField()
    auto_gen_toc = models.BooleanField(verbose_name="Auto Generate Table of Content",default=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICE, default="Draft")
    category_slug = models.SlugField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.category:
            self.category_slug = slugify(self.category)
        else:
            self.category_slug = "-"
        if self.auto_gen_toc:
            soup = BeautifulSoup(self.content, 'html.parser')
            all_h2 = soup.select("h2")
            toc_html = '<div class="card toc"> <div class="card-header"> In This Article </div> <div class="card-body">'
            toc_html += '<ul>'
            content = str(soup)
            for h2 in all_h2:
                if h2.text:
                    text = h2.text.strip()
                    text_slug = slugify(text)
                    li_anchor_html = f'<li><a href="#{text_slug}">{text}</a></li>'
                    toc_html += li_anchor_html
                    
                    old_h2 = str(h2).strip()
                    new_h2 = f'<h2 id="{text_slug}">{text}</h2>'
                    content = content.replace(old_h2,new_h2)
            toc_html += "</ul> </div> </div>"
            self.toc = toc_html
            self.content = content
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.url_slug


class BlogMention(models.Model):
    blog=models.ForeignKey(Blog, on_delete=models.CASCADE,related_name="mentions")
    type=models.CharField(max_length=50, default="thing")
    name=models.CharField(max_length=100)
    same_as=models.URLField(max_length=200)


class BlogAbout(models.Model):
    blog=models.ForeignKey(Blog, on_delete=models.CASCADE,related_name="abouts")
    type=models.CharField(max_length=50, default="thing")
    name=models.CharField(max_length=100)
    same_as=models.URLField(max_length=200)


class BlogCitation(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE,related_name="citations")
    headline = models.CharField(max_length=500)
    url = models.URLField(max_length=500)

guides/views.py
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.urls import reverse
from .models import *
from bs4 import BeautifulSoup
from .utils import generateWebPageSchema
from web_app.utils import renderTemplate
from django.utils.html import strip_tags
from django.db.models import Count
from django.conf import settings
from django.core.paginator import Paginator


class FormatBlogsObj:
    def formatBlogs(self, blogs_obj):
        formatted_blogs = []
        for blog in blogs_obj:
            temp = {}
            content = blog.content
            soup = BeautifulSoup(content, 'html.parser')
            temp["title"] = blog.meta_title
            temp["img"] = self.getImg(soup)
            if not temp["img"] and blog.featured_image:
                temp["img"] = blog.featured_image.url
            temp["img_alt"] = self.getImgAlt(temp["img"])
            temp["link"] = reverse("guides:blog_url",args=[blog.url_slug])
            temp["category"] = blog.category
            temp["category_slug"] = blog.category_slug
            temp["date"] = blog.created_at
            temp["author"] = blog.created_by
            temp["description"] = strip_tags(str(soup))
            if temp["title"] and temp["img"]:
                formatted_blogs.append(temp)
        return formatted_blogs

    def getImg(self,soup):
        images = soup.select("img")        
        for img in images:
            if img.get("src"):
                img = img["src"]
                return img
        return None
    
    def getImgAlt(self,img_url):
        alt_text = None
        if img_url:
            img_url = img_url.split("/")[-1]
            alt_text = img_url.split(".")[0]
        return alt_text



class HomePageView(TemplateView, FormatBlogsObj):
    template_name = "guides/home_page.html"
    extra_context = {}

    def get(self, *args, **kwargs):
        category_slug = kwargs.get("category_slug")
        if category_slug:
            self.request.extra_context = {"page_url" : "articles/{{x}}"}
            all_blogs = Blog.objects.filter(category_slug=category_slug, content__icontains="<img").order_by("-created_at")
        else:
            self.request.extra_context = {"page_url" : "articles"}
            all_blogs = Blog.objects.all().order_by("-created_at")
        if not all_blogs:
            raise Http404
        
        all_formatted_blogs = self.formatBlogs(all_blogs)
        paginator = Paginator(all_formatted_blogs, settings.ARTICLES_PAGINATION_LIMIT)
        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        latest_blog_obj = Blog.objects.filter(status="published").order_by("-created_at")[:settings.RECENT_ARTICLES_LIMIT]
        self.extra_context["page_obj"] = page_obj
        self.extra_context["latest_blogs"] = self.formatBlogs(latest_blog_obj)
        self.extra_context["categories"] = Blog.objects.values("category","category_slug").annotate(count=Count("category_slug")).filter(category__isnull=False, content__icontains="<img").order_by("-count")[:settings.TOP_CATEGORIES_LIMIT]
        self.extra_context["category"] = all_blogs.first().category
        self.extra_context["category_slug"] = category_slug
        self.request.extra_context["context"] = self.extra_context.copy()
        return super().get(*args, **kwargs)


class BlogView(TemplateView, FormatBlogsObj):
    template_name = "guides/blog_page.html"
    extra_context = {}


    def get(self, *args, **kwargs):
        url_slug = kwargs.get("url_slug")
        blog_obj = get_object_or_404(Blog, url_slug=url_slug,status="published")
        self.extra_context["blog_obj"] = blog_obj
        latest_blog_obj = Blog.objects.filter(status="published").order_by("-created_at")[:settings.RECENT_ARTICLES_LIMIT]
        self.extra_context["latest_blogs"] = self.formatBlogs(latest_blog_obj)
        
        url_prefix = f"{self.request.scheme}://{self.request.get_host()}"
        self.extra_context["meta_title"] = blog_obj.meta_title
        self.extra_context["meta_desc"] = blog_obj.meta_desc
        soup = BeautifulSoup(blog_obj.content, 'html.parser')
        first_img = self.getImg(soup)
        if blog_obj.featured_image:
            self.extra_context["meta_img_url"] = blog_obj.featured_image.url
        elif first_img:
            self.extra_context["meta_img_url"] = first_img
        else:
            self.extra_context["meta_img_url"] = "/static/default_featured_image.jpg"
        
        self.extra_context["web_page_schema"] = generateWebPageSchema(blog_obj,url_prefix)
        self.extra_context["blog_obj"].content = renderTemplate(blog_obj.content, {"toc":blog_obj.toc})
        self.extra_context["categories"] = Blog.objects.values("category","category_slug").annotate(count=Count("category_slug")).filter(category__isnull=False, content__icontains="<img").order_by("-count")[:settings.TOP_CATEGORIES_LIMIT]
        return super().get(*args, **kwargs)

guides/templates/guides/blog_page.html
{% extends 'base.html' %}
{% load static %}


{% block schema %}
{% if web_page_schema %}{{web_page_schema|safe}}{% endif %}
{% endblock schema %}


{% block style %}
<link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% endblock style %}


{% block body %}
<div class="container mt-4">
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb custom">
			<li class="breadcrumb-item"><a href="/">Home</a></li>
			<li class="breadcrumb-item"><a href="{% url 'guides:home_url' %}">Articles</a></li>
			{% if blog_obj.category %}
			<li class="breadcrumb-item"><a href="{% url 'guides:category_url' blog_obj.category_slug %}">{{blog_obj.category}}</a></li>
			{% endif %}
			<li class="breadcrumb-item active" aria-current="page">{{meta_title}}</li>
		</ol>
	</nav>

	<div class="row">
		<div class="col-lg-7 col-xl-8 mb-3">
			<h1>{{blog_obj.meta_title}}</h1>
			<small>{{blog_obj.created_at|date:"F d, Y"}}</small>
			<p class="mb-0 pb-0">
				Medically reviewed by
				<a href="{% url 'web_app:doctor_url' blog_obj.reviewed_by.slug %}"
					target="_blank">{{blog_obj.reviewed_by}}</a>
			</p>
			<p>
				By
				<a href="{% url 'web_app:doctor_url' blog_obj.created_by.slug %}"
					target="_blank">{{blog_obj.created_by}}</a>
			</p>

			<div class="guides">
				{{blog_obj.content|safe}}
			</div>


			{% if blog_obj.citations.all %}
			<h3><b>References:</b></h3>
			<div class="references">
				<ol>
					{% for citation in blog_obj.citations.all %}
					<li>
						<span>{{citation.headline}}</span>
						<br>
						<cite>
							<a href="{{citation.url}}" target="_blank"
								rel="follow noopener noreferrer">{{citation.url}}</a>
						</cite>
					</li>
					{% endfor %}
				</ol>
			</div>
			{% endif %}

		</div> <!-- Left side div -->

		<div class="recent-blogs-links col-lg-5 col-xl-4">
			{% include 'guides/recent_blogs_rightside.html' %}
		</div> <!-- Right side div -->
	</div> <!-- row -->
</div>
{% endblock body %}

guides/templates/guides/home_page.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
<link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% endblock style %}


{% block body %}
<div class="container mt-4">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb custom">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            {% if category_slug %}
            <li class="breadcrumb-item"><a href="{% url 'guides:home_url' %}">Articles</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{category}}</li>
            {% else %}
            <li class="breadcrumb-item active" aria-current="page">Articles</li>
            {% endif %}
        </ol>
    </nav>

    <div class="row">
        <div class="col-lg-7 col-xl-8">
            {% for blog in page_obj %}
            <div class="blog mb-5">
                <a href="{{blog.link}}">
                    <h1>{{blog.title}}</h1>
                </a>
                <div class="row mb-3 mt-2 blog-icons">
                    <div class="col-auto">
                        <i class="fas fa-calendar-alt"></i>
                        <span class="pl-1">{{blog.date.date}}</span>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-user"></i>
                        <a class="hover-primary-color" href="{% url 'web_app:doctor_url' blog.author.slug %}"
                            class="pl-1">{{blog.author.name}}</a>
                    </div>
                    {% if blog.category %}
                    <div class="col-auto">
                        <i class="fas fa-tag"></i>
                        <a class="hover-primary-color" href="{% url 'guides:category_url' blog.category_slug %}" class="pl-1">{{blog.category}}</a>
                    </div>
                    {% endif %}
                </div>
                <a href="{{blog.link}}">
                    <div class="img-bg-div" style="background-image: url('{{blog.img}}');"></div>
                </a>
                <p>{{blog.description|truncatechars:255}}</p>
            </div>
            {% endfor %}
            
            {% if page_obj.has_next %}
            <div class="d-flex blog-pagination mb-5">
                {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-default btn-outline-primary-theme" role="button">
                    <i class="fas fa-chevron-left"></i>
                    Older Posts
                </a>
                {% endif %}
                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="btn btn-default btn-outline-primary-theme ml-auto" role="button">
                    Newer Posts 
                    <i class="fas fa-chevron-right"></i>
                </a>
                {% endif %}
            </div>
            {% endif %}

        </div> <!-- Left side div -->

        <div class="recent-blogs-links col-lg-5 col-xl-4">
            {% include 'guides/recent_blogs_rightside.html' %}
        </div> <!-- Right side div -->
    </div> <!-- row -->
</div>
{% endblock body %}

guides/templates/guides/recent_blogs_rightside.html
<h3 style="font-weight: 600;">Recent Articles</h3>
<ul class="p-2">
    {% for guide in latest_blogs %}
    <li class="mb-3">
        <a class="row no-gutters" href="{{guide.link}}">
            <img class="pr-2 sm-img col-5" alt="{{guide.img_alt}}" src="{{guide.img}}">
            <span class="col-7">{{guide.title|truncatechars:60}}</span>
        </a>
    </li>
    {% endfor %}
</ul>

<br>
<h3 style="font-weight: 600;">Categories</h3>
<ul id="ul-categories" class="p-2">
    {% for data in categories %}
    <a href="{% url 'guides:category_url' data.category_slug %}">
        <li class="card-effect">
            <span>{{data.category}}</span>
            <span style="font-size: small;">({{data.count}})</span>
            <i class="fas fa-tag float-right mt-1"></i>
        </li>
    </a>
    {% endfor %}
</ul>