HospitalWebProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web_app.urls")),
    path('', include("guides.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # Serving media files
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
]

guides/urls.py
from django.urls import path
from .views import *

app_name = "guides"

urlpatterns = [
    path('articles/', HomePageView.as_view(), name="home_url"),
    path('articles/<slug:category_slug>/', HomePageView.as_view(), name="category_url"),
    path('<slug:url_slug>/', BlogView.as_view(), name="blog_url"),
]

web_app/urls.py
from django.urls import path
from .views import *

app_name = "web_app"

urlpatterns = [
    path("", HomePageView.as_view(), name="home_url"),
    path("doctors/<slug:doctor_slug>/", DoctorPageView.as_view(), name="doctor_url"),
    path('contact-us/', contact, name="contact_us_url"),
    path('services/<slug:service_name>/',services,name='services'),
    path('about-us/',about_us.as_view(),name='about_us'),
]

web_app/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
from django.core.exceptions import ValidationError


class CustomSiteContent(models.Model):
    STATUS_CHOICE = (
        ("draft", "Draft"),
        ("published", "Published")
    )
    site_name = models.CharField(max_length=255)
    site_url = models.CharField(max_length=255)
    logo = models.ImageField(upload_to="logo/")
    favicon = models.ImageField(upload_to="logo/")
    nav_brand_html = RichTextUploadingField()
    nav_html = RichTextUploadingField()
    footer_html = RichTextUploadingField(null=True, blank=True)
    nav_icon_html = models.CharField(max_length=255, null=True, blank=True)
    social_links_html = models.TextField(null=True, blank=True)
    script = models.TextField(null=True, blank=True)
    copyright_text = models.CharField(max_length=255, null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICE, default="draft")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.site_name} - {self.status}"


class CustomPageContent(models.Model):
    STATUS_CHOICE = (
        ("draft", "Draft"),
        ("published", "Published")
    )
    url = models.CharField(max_length=255, unique=True)
    meta_title = models.CharField(max_length=255)
    meta_desc = models.CharField(max_length=255)
    featured_image = models.ImageField(upload_to="featured_images/", null=True, blank=True)
    top_img = models.ImageField(upload_to='images', null=True, blank=True)
    top_img_heading = models.CharField(max_length=255, null=True, blank=True)

    notice=RichTextUploadingField(blank=True)
    displayimage=models.ImageField(upload_to='images', null=True, blank=True)
    aboutDescript=RichTextUploadingField(null=True, blank=True)
    meetteam=RichTextUploadingField(null=True, blank=True)
    afterTeamContent=RichTextUploadingField(null=True, blank=True)
    
    status = models.CharField(max_length=20, choices=STATUS_CHOICE, default="draft")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.url

    def clean(self) -> None:
        self.url = self.url.strip("/") if self.url != "/" else self.url
        if not self.url:
            raise ValidationError("URL should not be empty or invalid URL")
        

class HomePage(models.Model):
    image = models.ImageField(upload_to='homepage/', verbose_name='large image')
    text = models.TextField(verbose_name='text on lagre image')
    about_us_heading = models.CharField(max_length=255, default='About Us')
    about_us_image = models.ImageField(upload_to='homepage/',verbose_name='about-us image')
    # about_us_text = models.TextField(verbose_name='about-us text')
    about_us_text = RichTextField(verbose_name='about-us text')
    service_heading = models.CharField(max_length=255, default='SERVICES')
    service_subheading = models.CharField(max_length=255, default='Excellent Medical Services')
    doctor_heading = models.CharField(max_length=255, default='Meet Our Team')
    doctor_subheading = models.CharField(max_length=255, default='Qualified Healthcare Professionals')
    testimonial_heading = models.CharField(max_length=255, default='TESTIMONIAL')
    testimonial_subheading = models.CharField(max_length=255, default='Patients Say About Our Services')

    def __str__(self):
        self.heading = "Home Page Data"
        return self.heading


# class HomePageServices(models.Model):
#     image = models.ImageField(upload_to='homepage/services')
#     imageTitle = models.CharField(max_length=255)
#     homePage = models.ForeignKey(HomePage, on_delete=models.CASCADE) 

class TESTIMONIAL(models.Model):
    image = models.ImageField(upload_to='homepage/testimonial',null=True,blank=True)
    Comment = models.TextField()
    customerName = models.CharField(max_length=255)
    homePage = models.ForeignKey(HomePage, on_delete=models.CASCADE)





######################################## Business Schema ########################################
STATUS_CHOICE = (
    ("Sunday", "Sunday"),
    ("Monday", "Monday"),
    ("Tuesday", "Tuesday"),
    ("Wednesday", "Wednesday"),
    ("Thursday", "Thursday"),
    ("Friday", "Friday"),
    ("Saturday", "Saturday"),
)

STATUS_PATIENT = (
    ("True", "True"),
    ("False", "False"),
)

class Currency(models.Model):
    currencyName = models.CharField(max_length=255)

    def __str__(self):
        return self.currencyName
    
class KnowsLanguage(models.Model):
    language = models.CharField(max_length=255)

    def __str__(self):
        return self.language


class Business(models.Model):

    type = models.CharField(max_length=255)
    map_id = models.URLField(max_length=1000)
    additional_Type = models.URLField(blank=True,null=True)
    medical_Specialty = models.CharField(max_length=255)
    curreny_Accepted = models.ManyToManyField(Currency)
    payment_Accepted = models.CharField(max_length=255)
    hasMap = models.URLField(max_length=1000)
    logo = models.ImageField(upload_to='logo/')
    telephone = models.CharField(max_length=255,blank=True,null=True)
    isAcceptingNewPatients = models.CharField(max_length=255, choices=STATUS_PATIENT,default='yes')
    knows_language = models.ManyToManyField(KnowsLanguage)
    url = models.URLField()
    name = models.CharField(max_length=255)
    AlternateName = models.CharField(max_length=255,blank=True,null=True)
    description = models.TextField(blank=True,null=True)
    disambiguatingDescription = models.TextField(blank=True,null=True)
    foundingDate = models.CharField(max_length=255)
    SameAs = models.TextField(blank=True,null=True)

    def __str__(self):
        return self.type

class Haspart(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    type = models.CharField(max_length=255, default="CreativeWork")
    url = models.URLField()

class OpeningHours(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    day = models.CharField(max_length=255, choices=STATUS_CHOICE)
    timming = models.CharField(max_length=255)

class Adress(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE, default="PostalAddress")
    type = models.CharField(max_length=255)
    postalCode = models.CharField(max_length=255)
    addressRegion = models.CharField(max_length=255)
    addressCountry = models.CharField(max_length=255)
    streetAddress = models.CharField(max_length=500)
    addressLocality = models.CharField(max_length=500)

class Geo(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    type = models.CharField(max_length=255,default="GeoCoordinates")
    name = models.CharField(max_length=255)
    postalCode = models.CharField(max_length=255)
    latitude = models.CharField(max_length=255)
    longitude = models.CharField(max_length=255)
    description = models.TextField(blank=True,null=True)

class AreaServed(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    type = models.CharField(max_length=255, default="City")
    name = models.CharField(max_length=255)
    url = models.URLField()

class ContactPoint(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    type = models.CharField(max_length=255,default="ContactPoint")
    contactType = models.CharField(max_length=255)
    telephone = models.CharField(max_length=255)
    email = models.CharField(max_length=255)

class Image(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    type = models.CharField(max_length=255,default="ImageObject")
    name = models.CharField(max_length=255)
    url = models.ImageField(upload_to='images/')
    creator = models.CharField(max_length=255)
    contentLocation = models.CharField(max_length=255)



class Question(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name




######################################## Doctor Schema ########################################
class Doctor(models.Model):
    GENDER_CHOICES = (
        ("male", "Male"),
        ("female", "Female")
    )
    STATUS_CHOICE = (
        ("draft", "Draft"), 
        ("published", "Published")
    )

    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    additional_name = models.CharField(max_length=255, null=True, blank=True)
    family_name = models.CharField(max_length=255, null=True, blank=True)
    given_name = models.CharField(max_length=255, null=True, blank=True)
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES, default="male")
    image = models.ImageField(upload_to="doctor_images/", null=True, blank=True)
    image_caption = models.CharField(max_length=255, null=True, blank=True)
    honorific_prefix = models.CharField(max_length=20, default="Dr.")
    honorific_suffix = models.CharField(max_length=20, null=True, blank=True)
    job_title = models.CharField(max_length=255)
    description = RichTextField()
    disambiguating_description = models.CharField(max_length=255, null=True, blank=True)
    additional_type = models.CharField(max_length=255, null=True, blank=True)
    is_part_of = models.URLField(null=True, blank=True)
    publisher = models.ForeignKey(Business, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICE, default="Draft")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)
    

web_app/views.py
from django.views.generic import TemplateView,ListView
from .utils import *
from .models import *
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.utils.text import Truncator
from django.conf import settings


class HomePageView(TemplateView):
    template_name = "web_app/home.html"
    extra_context = {}

    def get(self, request, *args, **kwargs):
        request.extra_context = {"page_url" : "/"}
        home = HomePage.objects.prefetch_related('testimonial_set',).latest('id')
        self.extra_context["services"] = Service.objects.filter(status="published").values("name","slug","image","image_caption")[:settings.SERVICES_LIMIT]
        self.extra_context["testimonial"] = home.testimonial_set.all()
        self.extra_context["home"] = home
        doctors = Doctor.objects.prefetch_related('social_links').filter(status="published")
        for doctor in doctors:
            doctor.description = Truncator(doctor.description).chars(80, html=True)
            if not doctor.image:
                if doctor.gender == "male":
                    doctor.gender_image = 'default_male_doctor_profile_pic.png'
                else:
                    doctor.gender_image = 'default_female_doctor_profile_pic.png'
        k=CustomPageContent.objects.filter(url="/")
        self.extra_context["customdata"] = k[0]
        self.extra_context["doctors"] = doctors
        self.extra_context["businessSchema"] = generateBusinessSchema(request.build_absolute_uri())
        return super().get(request, *args, **kwargs)
        


class DoctorPageView(TemplateView):
    template_name = "web_app/doctor_page.html"
    extra_context = {}

    def get(self, request, *args, **kwargs):
        request.extra_context = {"page_url" : "doctors/{{x}}"}
        doctor_slug = kwargs.get("doctor_slug","null")
        doctor_obj = get_object_or_404(Doctor,slug=doctor_slug,status="published")
        url_prefix = f"{request.scheme}://{request.get_host()}"
        doctor_image_caption = doctor_obj.name
        if doctor_obj.image:
            doctor_image_url = doctor_obj.image.url
            doctor_image_caption = doctor_obj.image_caption
        elif doctor_obj.gender == "male":
            doctor_image_url = f"{url_prefix}/static/default_male_doctor_profile_pic.png"
        else:
            doctor_image_url = f"{url_prefix}/static/default_female_doctor_profile_pic.png"
        self.extra_context["doctor_obj"] = doctor_obj
        self.extra_context["meta_img_url"] = doctor_image_url
        self.extra_context["doctor_image_caption"] = doctor_image_caption
        self.extra_context["doctor_schema"] = generatePersonSchemaForDoctor(doctor_obj,url_prefix,doctor_image_url,doctor_image_caption)
        doctor_dict = doctor_obj.__dict__
        doctor_profile_table_data = [
            ("Specializations", doctor_dict["job_title"]),
            ("Expertise", ", ".join(doctor_obj.expertise.values_list("name",flat=True))),
            ("Occupation", f"{doctor_obj.occupations.first().name.title()} ({doctor_obj.occupations.first().description})"),
        ]
        self.extra_context["doctor_profile_table_data"] = doctor_profile_table_data
        self.extra_context["doctor_extra_informations"] = doctor_obj.extra_informations.filter(visibility=True).order_by("ordering")
        k=CustomPageContent.objects.filter(url="doctors/{{x}}")
        self.extra_context["customdata"] = k[0]


        all_doctors = Doctor.objects.prefetch_related('social_links').filter(status="published")
        for doctor in all_doctors:
            doctor.description = Truncator(doctor.description).chars(80, html=True)
            if not doctor.image:
                if doctor.gender == "male":
                    doctor.gender_image = 'default_male_doctor_profile_pic.png'
                else:
                    doctor.gender_image = 'default_female_doctor_profile_pic.png'
        self.extra_context["all_doctors"] = all_doctors

        request.extra_context["context"] = self.extra_context.copy()
        return super().get(request, *args, **kwargs)
    

def contact(request):
    request.extra_context = {"page_url" : "contact-us"}
    business = Business.objects.prefetch_related('openinghours_set', 'adress_set', 'contactpoint_set',).get(type="Physician")

    oh = business.openinghours_set.all()
    add = business.adress_set.all()
    ct = business.contactpoint_set.all()

    if request.POST:
        name = request.POST["name"]
        email = request.POST["email"]
        message = request.POST["message"]
        question = Question(name=name,email=email,comment=message)
        question.save()
    k=CustomPageContent.objects.filter(url="contact-us")

    context = {"oh":oh,"add":add,"ct":ct,"map":business.map_id,"customdata":k[0]}
    context["businessSchema"] = generateBusinessSchema(request.build_absolute_uri())
    request.extra_context["context"] = context
    return render(request,"web_app/contact.html",context)


def services(requests,service_name):
    requests.extra_context = {"page_url" : "services/{{x}}"}
    service_obj = get_object_or_404(Service,slug=service_name,status="published")
    provider_obj = Business.objects.all().first()
    k=CustomPageContent.objects.filter(url="services/{{x}}")
    context={
        "service_obj":service_obj,
        "provider":provider_obj.map_id,
        "contact_number":provider_obj.contactpoint_set.all().first().telephone,
        "all_services": Service.objects.all(),
        "service_name":service_name,
        "customdata":k[0]
    }

    requests.extra_context["context"] = context
    return render(requests,template_name="web_app/service_page.html",context=context)


class about_us(ListView):
    model = Doctor
    template_name="web_app/about_page.html"
    paginate_by=4
    context_object_name="docdata"
    extra_context = {}

    def get(self, request, *args, **kwargs):
        request.extra_context = {"page_url" : "about-us"}
        k=CustomPageContent.objects.filter(url="about-us")
        self.extra_context["customdata"] = k[0]
        self.extra_context["businessSchema"] = generateBusinessSchema(request.build_absolute_uri())
        request.extra_context["context"] = self.extra_context.copy()
        return super().get(request, *args, **kwargs)

web_app/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="{{request.scheme}}://{{request.get_host}}{{site_favicon}}">
    <link rel="canonical" href="{{request.build_absolute_uri}}">
    <!-- COMMON TAGS -->
    <title>{{meta_title}} - {{site_url}}</title>
    <!-- Search Engine -->
    <meta name="description" content="{{meta_desc}}">
    <meta name="image" content="{{request.scheme}}://{{request.get_host}}{{meta_img_url}}">
    <!-- Schema.org for Google -->
    <meta itemprop="name" content="{{meta_title}} - {{site_url}}">
    <meta itemprop="description" content="{{meta_desc}}">
    <meta itemprop="image" content="{{request.scheme}}://{{request.get_host}}{{meta_img_url}}">
    <!-- Twitter -->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="{{meta_title}} - {{site_url}}">
    <meta name="twitter:description" content="{{meta_desc}}">
    <meta name="twitter:image:src" content="{{request.scheme}}://{{request.get_host}}{{meta_img_url}}">
    <!-- Twitter - Article -->
    <!-- Open Graph general (Facebook, Pinterest & Google+) -->
    <meta name="og:title" content="{{meta_title}} - {{site_url}}">
    <meta name="og:description" content="{{meta_desc}}">
    <meta name="og:image" content="{{request.scheme}}://{{request.get_host}}{{meta_img_url}}">
    <meta name="og:url" content="{{request.build_absolute_uri}}">
    <meta name="og:site_name" content="{{site_name}}">
    <meta name="og:type" content="article">
    <!-- Open Graph - Article -->

    {% block head %}
    {% endblock head %}

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link rel="stylesheet" href="{% static 'css/admin.css' %}">
    {% block style %}
    {% endblock style %}

    <!-- Schema -->
    {% block schema %}
    {% endblock schema %}

    <!-- Script -->
    {% if custom_site_content_obj.script %}
    {{custom_site_content_obj.script|safe}}
    {% endif %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark secondary-theme">
        <div class="container-fluid">
            <span class="navbar-brand">
                <a href="/">
                    {% if custom_site_content_obj.nav_brand_html %}
                        {{custom_site_content_obj.nav_brand_html|safe}}
                    {% endif %}
                </a>
            </span>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler"
                aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggler">
                {% if custom_site_content_obj.nav_html %}
                    {{custom_site_content_obj.nav_html|safe}}
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="m-0 p-0 text-center text-light small-heads" style="background-color:var(--primary-bg)">{{customdata.notice|safe}}</div>
    
    {% if request.path != "/" %}
    <div class="cover-img-bg-div" style="background-image: url('{{top_img.url}}');">
        <h1 class="title">{{cover_img_title}}</h1>
    </div>
    {% endif %}

    <div style="min-height: 70vh;">

    {% block body %}
    {% endblock body %}
    </div>



    <!-- Footer -->
    <footer class="text-lg-start primary-theme">

        {% if custom_site_content_obj.footer_html %}
            {{custom_site_content_obj.footer_html|safe}}
        {% endif %}
        
        <section class="pt-4"> 
            <div class="container">
                <!-- Grid row -->
                <div class="row">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mb-4">
                        <h6 class="text-center text-uppercase fw-bold mb-4">
                            Office Hours
                        </h6>
                        <table style="margin: auto;">
                            <tbody>
                                {% for i in oh %}
                                <tr>
                                    <td style="width:100px;">{{i.day}}</td>
                                    <td>{{i.timming}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- Grid column -->


                     <!-- Grid column -->
                     <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mb-4">
                        <h6 class="text-center text-uppercase fw-bold mb-4">
                            Our Services
                        </h6>
                        <table style="margin: auto;">
                            <tbody>
                                {% for i in six_services_obj %}
                                <tr>
                                    <td><a href="{% url 'web_app:services' i.slug %}" target="_blank"  class="text-white">{{i.name}}</a></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- Grid column -->

                    
                      <!-- Grid column -->
                      <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mb-4">
                        <h6 class="text-center text-uppercase fw-bold mb-4">
                            Recent Articles
                        </h6>
                        <table style="margin: auto;">
                            <tbody>
                                {% for article in recent_articles %}
                                <tr>
                                    <td><a href="{% url 'guides:blog_url' article.url_slug %}" target="_blank"  class="text-white">{{article.meta_title}}</a></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- Grid column -->

                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mb-4">
                        <h6 class="text-center text-uppercase fw-bold mb-4">Contact Us</h6>

                         <table style="margin: auto;">
                            <tbody>
                                {% for i in add %}
                                <tr>
                                    <td style="vertical-align: top;width: 21px;"><i class="bi bi-geo-alt"></i></td>
                                    <td>{{i.streetAddress}}, {{i.addressLocality}}
                                        {{i.addressRegion}}, {{i.addressCountry}}, {{i.postalCode}}</td>
                                </tr>
                                {% endfor %}

                                {% for i in ct %}
                                <tr>
                                    <td style="vertical-align: top;width: 21px;"><i class="bi bi-telephone"></i></td>
                                    <td>{{i.contactType}}<br>{{i.telephone}}</td>
                                </tr>
                                {% endfor %}
                                <tr>
                                    <td style="vertical-align: top;width: 21px;"><i class="bi bi-pin-map"></i></i></td>
                                    <td style="word-break: break-all;"><a href="{{map_id}}" target="_blank"  class="text-white">Locate us on Google Maps</a></td>
                                </tr>
                            </tbody>
                        </table>

                    </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row -->
            </div>
        </section>
        <!-- Section: Links  -->

        {% if custom_site_content_obj.social_links_html %}
            {{custom_site_content_obj.social_links_html|safe}}
        {% endif %}

        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
            {{custom_site_content_obj.copyright_text|safe}}
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->


    <!-- JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.2/js/bootstrap.bundle.min.js"></script>

    {% block script %}
    {% endblock script %}
</body>

</html>