HospitalWebProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web_app.urls")),
    path('', include("guides.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # Serving media files
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
]

guides/urls.py
from django.urls import path
from .views import *

app_name = "guides"

urlpatterns = [
    path('articles/', HomePageView.as_view(), name="home_url"),
    path('articles/<slug:category_slug>/', HomePageView.as_view(), name="category_url"),
    path('<slug:url_slug>/', BlogView.as_view(), name="blog_url"),
]

web_app/urls.py
from django.urls import path
from .views import *

app_name = "web_app"

urlpatterns = [
    path("", HomePageView.as_view(), name="home_url"),
    path("doctors/<slug:doctor_slug>/", DoctorPageView.as_view(), name="doctor_url"),
    path('contact-us/', contact, name="contact_us_url"),
    path('services/<slug:service_name>/',services,name='services'),
    path('about-us/',about_us.as_view(),name='about_us'),
]

web_app/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
from django.core.exceptions import ValidationError


class CustomSiteContent(models.Model):
    STATUS_CHOICE = (
        ("draft", "Draft"),
        ("published", "Published")
    )
    site_name = models.CharField(max_length=255)
    site_url = models.CharField(max_length=255)
    logo = models.ImageField(upload_to="logo/")
    favicon = models.ImageField(upload_to="logo/")
    nav_brand_html = RichTextUploadingField()
    nav_html = RichTextUploadingField()
    footer_html = RichTextUploadingField(null=True, blank=True)
    nav_icon_html = models.CharField(max_length=255, null=True, blank=True)
    social_links_html = models.TextField(null=True, blank=True)
    script = models.TextField(null=True, blank=True)
    copyright_text = models.CharField(max_length=255, null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICE, default="draft")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.site_name} - {self.status}"


class CustomPageContent(models.Model):
    STATUS_CHOICE = (
        ("draft", "Draft"),
        ("published", "Published")
    )
    url = models.CharField(max_length=255, unique=True)
    meta_title = models.CharField(max_length=255)
    meta_desc = models.CharField(max_length=255)
    featured_image = models.ImageField(upload_to="featured_images/", null=True, blank=True)
    top_img = models.ImageField(upload_to='images', null=True, blank=True)
    top_img_heading = models.CharField(max_length=255, null=True, blank=True)

    notice=RichTextUploadingField(blank=True)
    displayimage=models.ImageField(upload_to='images', null=True, blank=True)
    aboutDescript=RichTextUploadingField(null=True, blank=True)
    meetteam=RichTextUploadingField(null=True, blank=True)
    afterTeamContent=RichTextUploadingField(null=True, blank=True)
    
    status = models.CharField(max_length=20, choices=STATUS_CHOICE, default="draft")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.url

    def clean(self) -> None:
        self.url = self.url.strip("/") if self.url != "/" else self.url
        if not self.url:
            raise ValidationError("URL should not be empty or invalid URL")
        

class HomePage(models.Model):
    image = models.ImageField(upload_to='homepage/', verbose_name='large image')
    text = models.TextField(verbose_name='text on lagre image')
    about_us_heading = models.CharField(max_length=255, default='About Us')
    about_us_image = models.ImageField(upload_to='homepage/',verbose_name='about-us image')
    # about_us_text = models.TextField(verbose_name='about-us text')
    about_us_text = RichTextField(verbose_name='about-us text')
    service_heading = models.CharField(max_length=255, default='SERVICES')
    service_subheading = models.CharField(max_length=255, default='Excellent Medical Services')
    doctor_heading = models.CharField(max_length=255, default='Meet Our Team')
    doctor_subheading = models.CharField(max_length=255, default='Qualified Healthcare Professionals')
    testimonial_heading = models.CharField(max_length=255, default='TESTIMONIAL')
    testimonial_subheading = models.CharField(max_length=255, default='Patients Say About Our Services')

    def __str__(self):
        self.heading = "Home Page Data"
        return self.heading


# class HomePageServices(models.Model):
#     image = models.ImageField(upload_to='homepage/services')
#     imageTitle = models.CharField(max_length=255)
#     homePage = models.ForeignKey(HomePage, on_delete=models.CASCADE) 

class TESTIMONIAL(models.Model):
    image = models.ImageField(upload_to='homepage/testimonial',null=True,blank=True)
    Comment = models.TextField()
    customerName = models.CharField(max_length=255)
    homePage = models.ForeignKey(HomePage, on_delete=models.CASCADE)





######################################## Business Schema ########################################
STATUS_CHOICE = (
    ("Sunday", "Sunday"),
    ("Monday", "Monday"),
    ("Tuesday", "Tuesday"),
    ("Wednesday", "Wednesday"),
    ("Thursday", "Thursday"),
    ("Friday", "Friday"),
    ("Saturday", "Saturday"),
)

STATUS_PATIENT = (
    ("True", "True"),
    ("False", "False"),
)

class Currency(models.Model):
    currencyName = models.CharField(max_length=255)

    def __str__(self):
        return self.currencyName
    
class KnowsLanguage(models.Model):
    language = models.CharField(max_length=255)

    def __str__(self):
        return self.language


class Business(models.Model):

    type = models.CharField(max_length=255)
    map_id = models.URLField(max_length=1000)
    additional_Type = models.URLField(blank=True,null=True)
    medical_Specialty = models.CharField(max_length=255)
    curreny_Accepted = models.ManyToManyField(Currency)
    payment_Accepted = models.CharField(max_length=255)
    hasMap = models.URLField(max_length=1000)
    logo = models.ImageField(upload_to='logo/')
    telephone = models.CharField(max_length=255,blank=True,null=True)
    isAcceptingNewPatients = models.CharField(max_length=255, choices=STATUS_PATIENT,default='yes')
    knows_language = models.ManyToManyField(KnowsLanguage)
    url = models.URLField()
    name = models.CharField(max_length=255)
    AlternateName = models.CharField(max_length=255,blank=True,null=True)
    description = models.TextField(blank=True,null=True)
    disambiguatingDescription = models.TextField(blank=True,null=True)
    foundingDate = models.CharField(max_length=255)
    SameAs = models.TextField(blank=True,null=True)

    def __str__(self):
        return self.type

class Haspart(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    type = models.CharField(max_length=255, default="CreativeWork")
    url = models.URLField()

class OpeningHours(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    day = models.CharField(max_length=255, choices=STATUS_CHOICE)
    timming = models.CharField(max_length=255)

class Adress(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE, default="PostalAddress")
    type = models.CharField(max_length=255)
    postalCode = models.CharField(max_length=255)
    addressRegion = models.CharField(max_length=255)
    addressCountry = models.CharField(max_length=255)
    streetAddress = models.CharField(max_length=500)
    addressLocality = models.CharField(max_length=500)

class Geo(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    type = models.CharField(max_length=255,default="GeoCoordinates")
    name = models.CharField(max_length=255)
    postalCode = models.CharField(max_length=255)
    latitude = models.CharField(max_length=255)
    longitude = models.CharField(max_length=255)
    description = models.TextField(blank=True,null=True)

class AreaServed(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    type = models.CharField(max_length=255, default="City")
    name = models.CharField(max_length=255)
    url = models.URLField()

class ContactPoint(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    type = models.CharField(max_length=255,default="ContactPoint")
    contactType = models.CharField(max_length=255)
    telephone = models.CharField(max_length=255)
    email = models.CharField(max_length=255)

class Image(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    type = models.CharField(max_length=255,default="ImageObject")
    name = models.CharField(max_length=255)
    url = models.ImageField(upload_to='images/')
    creator = models.CharField(max_length=255)
    contentLocation = models.CharField(max_length=255)



class Question(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name




######################################## Doctor Schema ########################################
class Doctor(models.Model):
    GENDER_CHOICES = (
        ("male", "Male"),
        ("female", "Female")
    )
    STATUS_CHOICE = (
        ("draft", "Draft"), 
        ("published", "Published")
    )

    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    additional_name = models.CharField(max_length=255, null=True, blank=True)
    family_name = models.CharField(max_length=255, null=True, blank=True)
    given_name = models.CharField(max_length=255, null=True, blank=True)
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES, default="male")
    image = models.ImageField(upload_to="doctor_images/", null=True, blank=True)
    image_caption = models.CharField(max_length=255, null=True, blank=True)
    honorific_prefix = models.CharField(max_length=20, default="Dr.")
    honorific_suffix = models.CharField(max_length=20, null=True, blank=True)
    job_title = models.CharField(max_length=255)
    description = RichTextField()
    disambiguating_description = models.CharField(max_length=255, null=True, blank=True)
    additional_type = models.CharField(max_length=255, null=True, blank=True)
    is_part_of = models.URLField(null=True, blank=True)
    publisher = models.ForeignKey(Business, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICE, default="Draft")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)
    

web_app/views.py
from django.views.generic import TemplateView,ListView
from .utils import *
from .models import *
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.utils.text import Truncator
from django.conf import settings


class HomePageView(TemplateView):
    template_name = "web_app/home.html"
    extra_context = {}

    def get(self, request, *args, **kwargs):
        request.extra_context = {"page_url" : "/"}
        home = HomePage.objects.prefetch_related('testimonial_set',).latest('id')
        self.extra_context["services"] = Service.objects.filter(status="published").values("name","slug","image","image_caption")[:settings.SERVICES_LIMIT]
        self.extra_context["testimonial"] = home.testimonial_set.all()
        self.extra_context["home"] = home
        doctors = Doctor.objects.prefetch_related('social_links').filter(status="published")
        for doctor in doctors:
            doctor.description = Truncator(doctor.description).chars(80, html=True)
            if not doctor.image:
                if doctor.gender == "male":
                    doctor.gender_image = 'default_male_doctor_profile_pic.png'
                else:
                    doctor.gender_image = 'default_female_doctor_profile_pic.png'
        k=CustomPageContent.objects.filter(url="/")
        self.extra_context["customdata"] = k[0]
        self.extra_context["doctors"] = doctors
        self.extra_context["businessSchema"] = generateBusinessSchema(request.build_absolute_uri())
        return super().get(request, *args, **kwargs)
        


class DoctorPageView(TemplateView):
    template_name = "web_app/doctor_page.html"
    extra_context = {}

    def get(self, request, *args, **kwargs):
        request.extra_context = {"page_url" : "doctors/{{x}}"}
        doctor_slug = kwargs.get("doctor_slug","null")
        doctor_obj = get_object_or_404(Doctor,slug=doctor_slug,status="published")
        url_prefix = f"{request.scheme}://{request.get_host()}"
        doctor_image_caption = doctor_obj.name
        if doctor_obj.image:
            doctor_image_url = doctor_obj.image.url
            doctor_image_caption = doctor_obj.image_caption
        elif doctor_obj.gender == "male":
            doctor_image_url = f"{url_prefix}/static/default_male_doctor_profile_pic.png"
        else:
            doctor_image_url = f"{url_prefix}/static/default_female_doctor_profile_pic.png"
        self.extra_context["doctor_obj"] = doctor_obj
        self.extra_context["meta_img_url"] = doctor_image_url
        self.extra_context["doctor_image_caption"] = doctor_image_caption
        self.extra_context["doctor_schema"] = generatePersonSchemaForDoctor(doctor_obj,url_prefix,doctor_image_url,doctor_image_caption)
        doctor_dict = doctor_obj.__dict__
        doctor_profile_table_data = [
            ("Specializations", doctor_dict["job_title"]),
            ("Expertise", ", ".join(doctor_obj.expertise.values_list("name",flat=True))),
            ("Occupation", f"{doctor_obj.occupations.first().name.title()} ({doctor_obj.occupations.first().description})"),
        ]
        self.extra_context["doctor_profile_table_data"] = doctor_profile_table_data
        self.extra_context["doctor_extra_informations"] = doctor_obj.extra_informations.filter(visibility=True).order_by("ordering")
        k=CustomPageContent.objects.filter(url="doctors/{{x}}")
        self.extra_context["customdata"] = k[0]


        all_doctors = Doctor.objects.prefetch_related('social_links').filter(status="published")
        for doctor in all_doctors:
            doctor.description = Truncator(doctor.description).chars(80, html=True)
            if not doctor.image:
                if doctor.gender == "male":
                    doctor.gender_image = 'default_male_doctor_profile_pic.png'
                else:
                    doctor.gender_image = 'default_female_doctor_profile_pic.png'
        self.extra_context["all_doctors"] = all_doctors

        request.extra_context["context"] = self.extra_context.copy()
        return super().get(request, *args, **kwargs)
    

def contact(request):
    request.extra_context = {"page_url" : "contact-us"}
    business = Business.objects.prefetch_related('openinghours_set', 'adress_set', 'contactpoint_set',).get(type="Physician")

    oh = business.openinghours_set.all()
    add = business.adress_set.all()
    ct = business.contactpoint_set.all()

    if request.POST:
        name = request.POST["name"]
        email = request.POST["email"]
        message = request.POST["message"]
        question = Question(name=name,email=email,comment=message)
        question.save()
    k=CustomPageContent.objects.filter(url="contact-us")

    context = {"oh":oh,"add":add,"ct":ct,"map":business.map_id,"customdata":k[0]}
    context["businessSchema"] = generateBusinessSchema(request.build_absolute_uri())
    request.extra_context["context"] = context
    return render(request,"web_app/contact.html",context)


def services(requests,service_name):
    requests.extra_context = {"page_url" : "services/{{x}}"}
    service_obj = get_object_or_404(Service,slug=service_name,status="published")
    provider_obj = Business.objects.all().first()
    k=CustomPageContent.objects.filter(url="services/{{x}}")
    context={
        "service_obj":service_obj,
        "provider":provider_obj.map_id,
        "contact_number":provider_obj.contactpoint_set.all().first().telephone,
        "all_services": Service.objects.all(),
        "service_name":service_name,
        "customdata":k[0]
    }

    requests.extra_context["context"] = context
    return render(requests,template_name="web_app/service_page.html",context=context)


class about_us(ListView):
    model = Doctor
    template_name="web_app/about_page.html"
    paginate_by=4
    context_object_name="docdata"
    extra_context = {}

    def get(self, request, *args, **kwargs):
        request.extra_context = {"page_url" : "about-us"}
        k=CustomPageContent.objects.filter(url="about-us")
        self.extra_context["customdata"] = k[0]
        self.extra_context["businessSchema"] = generateBusinessSchema(request.build_absolute_uri())
        request.extra_context["context"] = self.extra_context.copy()
        return super().get(request, *args, **kwargs)

web_app/templates/web_app/home.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
<link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet">
<link href="{% static 'css/carousel.css' %}" rel="stylesheet">


{% endblock style %}


{% block schema %}
{% if businessSchema %}{{businessSchema|safe}}{% endif %}
{% endblock schema %}


{% block body %}
<!-- class="d-none d-md-block" -->
<!-- carousel start -->
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item item active">
            <img class="d-block w-100 h-100" src="{{home.image.url}}" alt="First slide" style="object-fit: cover;">
        </div>

        <div class="absolute-div">
            <div class="carousel-caption">
                <div class="caption-text">
                    <h1>{{home.text}}</h1>
                    <div class="sub-heading">
                        <a href="/contact-us/" class="btn py-md-3 px-md-5  rounded-pill  fw-bold">Appointment</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- carousel end -->

<!-- about us start -->
<div class="container-fluid py-5">
    <div class="container">
        <div class="row gx-5">
            <div class="col-lg-5 mb-5 mb-lg-0 display-none" style="min-height: 500px;">
                <div class="position-relative h-100">
                    <img class="position-absolute w-100 h-100 rounded" src="{{home.about_us_image.url}}"
                        style="object-fit: cover;">
                </div>
            </div>
            <div class="col-lg-7">
                <div class="mb-4 text-center">
                    <h1 class="d-inline-block  text-uppercase"
                        style="color: var(--primary-bg) !important; font-weight: bolder;">{{home.about_us_heading}}</h1>
                </div>
                <p>{{home.about_us_text|safe}} </p>
                <div class="row g-3 pt-3">
                    <div class="col-sm-3 col-6">
                        <div class="bg-light text-center rounded-circle py-4">
                            <i class="fa fa-3x fa-user-md mb-1" style="color: var(--primary-bg) !important"></i>
                            <h6 class="mb-0" style="color: var(--primary-bg) !important;">Qualified<small
                                    class="d-block">Doctors</small></h6>
                        </div>
                    </div>
                    <div class="col-sm-3 col-6">
                        <div class="bg-light text-center rounded-circle py-4">
                            <i class="fa fa-3x fa-teeth mb-1" style="color: var(--primary-bg) !important"></i>
                            <h6 class="mb-0" style="color: var(--primary-bg) !important;">Dental<small
                                    class="d-block">implant</small></h6>
                        </div>
                    </div>
                    <div class="col-sm-3 col-6">
                        <div class="bg-light text-center rounded-circle py-4">
                            <i class="fa fa-3x fa-tooth mb-1" style="color: var(--primary-bg) !important"></i>
                            <h6 class="mb-0" style="color: var(--primary-bg) !important;">Dental<small
                                    class="d-block">Extraction</small></h6>
                        </div>
                    </div>
                    <div class="col-sm-3 col-6">
                        <div class="bg-light text-center rounded-circle py-4">
                            <i class="fa fa-3x fa-microscope  mb-1" style="color: var(--primary-bg) !important"></i>
                            <h6 class="mb-0" style="color: var(--primary-bg) !important;">Accurate<small
                                    class="d-block">Check up</small></h6>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- about us end -->



 <!-- services start -->
<div class="container" id="services">
    <div class="text-center mx-auto mb-5" style="max-width: 500px;">
        <h1 class="d-inline-block  text-uppercase" style="color: var(--primary-bg) !important; font-weight: bolder;">
            {{home.service_heading}}</h1>
        <h3 class="display-4" style="font-weight: bolder;">{{home.service_subheading}}</h3>
    </div>
    <div class="row">
        {% for service in services %}
        <div class="col-md-4">
            <a href="{% url 'web_app:services' service.slug  %}" style="text-decoration: none;">
                <div class="card mb-4 box-shadow" style="background-color: var(--primary-bg);">
                    <img class="card-img-top"
                        data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail"
                        alt="{{service.image_caption}}" style="height: 225px; width: 100%; display: block;"
                        src="media/{{service.image}}" data-holder-rendered="true">
                    <h5 class="card-text text-center mt-1 text-white" style=" font-weight: bold;">{{service.name}}</h5>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
 <!-- services end -->


<!-- doctor start -->
<div class="container-fluid py-5" id="doctors">
    <div class="container">
        <div class="text-center mx-auto mb-5" style="max-width: 500px;">
            <h1 class="d-inline-block text-uppercase" style="color: var(--primary-bg) !important; font-weight: bolder;">
                {{home.doctor_heading}}</h1>
            <h1 class="display-4" style="font-weight: bold;">{{home.doctor_subheading}}</h1>
        </div>
        <div class="owl-carousel team-carousel position-relative">
            {% for doctor in doctors %}
            <div class="team-item">
                <div class="row g-0 bg-light rounded overflow-hidden">
                    <div class="col-12 col-sm-5 h-100">
                        {% if doctor.image %}
                        <img class="img-fluid h-100" src="{{doctor.image.url}}" style="object-fit: cover;">
                        {% else %}
                        <img class="img-fluid h-100" src="{% static doctor.gender_image %}" style="object-fit: cover;">
                        {% endif %}
                    </div>
                    <div class="col-12 col-sm-7 h-100 d-flex flex-column">
                        <a style="text-decoration: none;color: black;" href="{% url 'web_app:doctor_url' doctor.slug %}">
                            <div class="mt-auto p-4">
                                <h6 class="font-weight-bold">{{doctor.name}} </h6>
                                <h6 class="font-weight-bold  mb-2" style="color: var(--primary-bg) !important;">
                                    {{doctor.job_title}}</h6>
                                    {{doctor.description|safe}}
                            </div>
                        </a>
                        <div class="d-flex mt-auto border-top p-4">
                            {% for social in doctor.social_links.all %}
                            <a class="btn btn-lg  btn-lg-square rounded-circle" href="{{social.url}}" ><i
                                    class="fab fa-{{social.name}}"></i></a>
                        {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
           
            {% for doctor in doctors %}
            <div class="team-item">
                <div class="row g-0 bg-light rounded overflow-hidden">
                    <div class="col-12 col-sm-5 h-100">
                        {% if doctor.image %}
                        <img class="img-fluid h-100" src="{{doctor.image.url}}" style="object-fit: cover;">
                        {% else %}
                        <img class="img-fluid h-100" src="{% static doctor.gender_image %}" style="object-fit: cover;">
                        {% endif %}
                    </div>
                    <div class="col-12 col-sm-7 h-100 d-flex flex-column">
                        <a style="text-decoration: none;color: black;" href="{% url 'web_app:doctor_url' doctor.slug %}">
                            <div class="mt-auto p-4">
                                <h6 class="font-weight-bold">{{doctor.name}} </h6>
                                <h6 class="font-weight-bold  mb-2" style="color: var(--primary-bg) !important;">
                                    {{doctor.job_title}}</h6>
                                    {{doctor.description|safe}}
                            </div>
                        </a>
                        <div class="d-flex mt-auto border-top p-4">
                            {% for social in doctor.social_links.all %}
                            <a class="btn btn-lg  btn-lg-square rounded-circle" href="{{social.url}}" ><i
                                    class="fab fa-{{social.name}}"></i></a>
                        {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
          
        </div>
    </div>
</div>
<!-- doctor end -->







<!-- Testimonial Start -->
<div class="container-fluid py-5">
    <div class="container">
        <div class="text-center mx-auto mb-5" style="max-width: 500px;">
            <h2 class="d-inline-block  text-uppercase"
                style="color: var(--primary-bg) !important; font-weight: bolder;">{{home.testimonial_heading}}</h2>
            <h1 class="display-4" style="font-weight: bolder;">{{home.testimonial_subheading}}</h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="owl-carousel testimonial-carousel">

                    {% for i in testimonial %}
                    <div class="testimonial-item text-center">
                        <div class="position-relative mb-5">
                            {% if i.image %}
                            <img class="img-fluid rounded-circle mx-auto" src="{{i.image.url}}" alt="">
                            {% else %}
                            <img class="img-fluid rounded-circle mx-auto" src="{% static 'default_testimonal_image.png' %}" alt="">
                            {% endif %}
                            <div class="position-absolute top-100 start-50 translate-middle d-flex align-items-center justify-content-center bg-white rounded-circle"
                                style="width: 60px; height: 60px;">
                            </div>
                        </div>
                        <p style="font-weight: bolder;">{{i.Comment}}</p>
                        <hr class="w-25 mx-auto">
                        <h4 style="font-weight: bolder;color: var(--primary-bg) !important;">{{i.customerName}}</h4>
                      
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
</div>
<!-- Testimonial End -->








{% endblock body %}




{% block script %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>

<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

<script src="{% static 'js/carousel.js' %}"></script>


{% endblock script %}